name: dotnet publish

on:
  release:
    types: [ "published" ]
    
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run the Cake script
      uses: cake-build/cake-action@v1
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      with:
        script-path: build.cake
        target: Pack
        arguments: |
          packageversion: "${{ github.event.release.tag_name }}"
